version: '3'

networks:
  web_net:
    external: true

services:
  vueui:
    container_name: hex-lowcode-engine
    image: swr.cn-north-4.myhuaweicloud.com/yuanjunjie/hex-lowcode-engine:dev
    restart: always
    networks:
      - web_net
    ports:
      - '8087:80'
