import {
  StepBackwardOutlined,
  StepForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  UpCircleOutlined,
  DownCircleOutlined,
  LeftCircleOutlined,
  RightCircleOutlined,
  DoubleRightOutlined,
  DoubleLeftOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VerticalAlignTopOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined,
  ForwardOutlined,
  BackwardOutlined,
  RollbackOutlined,
  EnterOutlined,
  RetweetOutlined,
  SwapOutlined,
  SwapLeftOutlined,
  SwapRightOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  PlayCircleFilled,
  UpSquareOutlined,
  DownSquareOutlined,
  LeftSquareOutlined,
  RightSquareOutlined,
  LoginOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderOuterOutlined,
  BorderLeftOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  RadiusBottomleftOutlined,
  RadiusBottomrightOutlined,
  RadiusUpleftOutlined,
  RadiusUprightOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  QuestionOutlined,
  QuestionCircleOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  PauseOutlined,
  PauseCircleOutlined,
  MinusOutlined,
  MinusCircleOutlined,
  PlusSquareOutlined,
  MinusSquareOutlined,
  InfoOutlined,
  InfoCircleOutlined,
  ExclamationOutlined,
  ExclamationCircleOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CloseSquareOutlined,
  CheckOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  WarningOutlined,
  IssuesCloseOutlined,
  StopOutlined,
  EditOutlined,
  FormOutlined,
  CopyOutlined,
  ScissorOutlined,
  DeleteOutlined,
  SnippetsOutlined,
  DiffOutlined,
  HighlightOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  BgColorsOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  RedoOutlined,
  UndoOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  LineHeightOutlined,
  DashOutlined,
  SmallDashOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  DragOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  RadiusSettingOutlined,
  ColumnWidthOutlined,
  ColumnHeightOutlined,
  AreaChartOutlined,
  PieChartFilled,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  RadarChartOutlined,
  HeartOutlined,
  FallOutlined,
  RiseOutlined,
  StockOutlined,
  BoxPlotOutlined,
  FundOutlined,
  SlidersOutlined,
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AppstoreAddOutlined,
  AudioOutlined,
  AudioMutedOutlined,
  AuditOutlined,
  BankOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BorderOutlined,
  BorderlessTableOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CarryOutFilled,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  CloudOutlined,
  CloudDownloadOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyrightCircleOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DingdingOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DownloadOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddFilled,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  FolderViewOutlined,
  ForkOutlined,
  FormatPainterOutlined,
  FrownOutlined,
  FunctionOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GlobalOutlined,
  GoldOutlined,
  GroupOutlined,
  HddOutlined,
  HistoryOutlined,
  HolderOutlined,
  HomeOutlined,
  HourglassOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LikeOutlined,
  LineOutlined,
  LinkOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MehOutlined,
  MenuOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlaySquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  ReloadOutlined,
  RestOutlined,
  RobotOutlined,
  RocketOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SisternodeOutlined,
  SkinOutlined,
  SmileOutlined,
  SolutionOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  SubnodeOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  UngroupOutlined,
  UnlockFilled,
  UploadOutlined,
  UserOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WomanOutlined,
  UsbOutlined,
  EditFilled,
  CopyFilled,
  DeleteFilled,
  SnippetsFilled,
  DiffFilled,
  HighlightFilled,
  EditTwoTone,
  CopyTwoTone,
  DeleteTwoTone,
  SnippetsTwoTone,
  DiffTwoTone,
  HighlightTwoTone,
} from '@ant-design/icons-vue/lib/icons';

export const data = [
  {
    label: '线性风格',
    value: [
      {
        label: '方向性图标',
        children: [
          {
            label: 'StepBackwardOutlined',
            value: StepBackwardOutlined,
          },
          {
            label: 'StepForwardOutlined',
            value: StepForwardOutlined,
          },
          {
            label: 'FastBackwardOutlined',
            value: FastBackwardOutlined,
          },
          {
            label: 'FastForwardOutlined',
            value: FastForwardOutlined,
          },
          {
            label: 'ShrinkOutlined',
            value: ShrinkOutlined,
          },
          {
            label: 'ArrowsAltOutlined',
            value: ArrowsAltOutlined,
          },
          {
            label: 'DownOutlined',
            value: DownOutlined,
          },
          {
            label: 'UpOutlined',
            value: UpOutlined,
          },
          {
            label: 'LeftOutlined',
            value: LeftOutlined,
          },
          {
            label: 'RightOutlined',
            value: RightOutlined,
          },
          {
            label: 'CaretUpOutlined',
            value: CaretUpOutlined,
          },
          {
            label: 'CaretDownOutlined',
            value: CaretDownOutlined,
          },
          {
            label: 'CaretLeftOutlined',
            value: CaretLeftOutlined,
          },
          {
            label: 'CaretRightOutlined',
            value: CaretRightOutlined,
          },
          {
            label: 'UpCircleOutlined',
            value: UpCircleOutlined,
          },
          {
            label: 'DownCircleOutlined',
            value: DownCircleOutlined,
          },
          {
            label: 'LeftCircleOutlined',
            value: LeftCircleOutlined,
          },
          {
            label: 'RightCircleOutlined',
            value: RightCircleOutlined,
          },
          {
            label: 'DoubleRightOutlined',
            value: DoubleRightOutlined,
          },
          {
            label: 'DoubleLeftOutlined',
            value: DoubleLeftOutlined,
          },
          {
            label: 'VerticalLeftOutlined',
            value: VerticalLeftOutlined,
          },
          {
            label: 'VerticalRightOutlined',
            value: VerticalRightOutlined,
          },
          {
            label: 'VerticalAlignTopOutlined',
            value: VerticalAlignTopOutlined,
          },
          {
            label: 'VerticalAlignMiddleOutlined',
            value: VerticalAlignMiddleOutlined,
          },
          {
            label: 'VerticalAlignBottomOutlined',
            value: VerticalAlignBottomOutlined,
          },
          {
            label: 'ForwardOutlined',
            value: ForwardOutlined,
          },
          {
            label: 'BackwardOutlined',
            value: BackwardOutlined,
          },
          {
            label: 'RollbackOutlined',
            value: RollbackOutlined,
          },
          {
            label: 'EnterOutlined',
            value: EnterOutlined,
          },
          {
            label: 'RetweetOutlined',
            value: RetweetOutlined,
          },
          {
            label: 'SwapOutlined',
            value: SwapOutlined,
          },
          {
            label: 'SwapLeftOutlined',
            value: SwapLeftOutlined,
          },
          {
            label: 'SwapRightOutlined',
            value: SwapRightOutlined,
          },
          {
            label: 'ArrowUpOutlined',
            value: ArrowUpOutlined,
          },
          {
            label: 'ArrowDownOutlined',
            value: ArrowDownOutlined,
          },
          {
            label: 'ArrowLeftOutlined',
            value: ArrowLeftOutlined,
          },
          {
            label: 'ArrowRightOutlined',
            value: ArrowRightOutlined,
          },
          {
            label: 'PlayCircleFilled',
            value: PlayCircleFilled,
          },
          {
            label: 'UpSquareOutlined',
            value: UpSquareOutlined,
          },
          {
            label: 'DownSquareOutlined',
            value: DownSquareOutlined,
          },
          {
            label: 'LeftSquareOutlined',
            value: LeftSquareOutlined,
          },
          {
            label: 'RightSquareOutlined',
            value: RightSquareOutlined,
          },
          {
            label: 'LoginOutlined',
            value: LoginOutlined,
          },
          {
            label: 'LogoutOutlined',
            value: LogoutOutlined,
          },
          {
            label: 'MenuFoldOutlined',
            value: MenuFoldOutlined,
          },
          {
            label: 'MenuUnfoldOutlined',
            value: MenuUnfoldOutlined,
          },
          {
            label: 'BorderBottomOutlined',
            value: BorderBottomOutlined,
          },
          {
            label: 'BorderHorizontalOutlined',
            value: BorderHorizontalOutlined,
          },
          {
            label: 'BorderInnerOutlined',
            value: BorderInnerOutlined,
          },
          {
            label: 'BorderOuterOutlined',
            value: BorderOuterOutlined,
          },
          {
            label: 'BorderLeftOutlined',
            value: BorderLeftOutlined,
          },
          {
            label: 'BorderRightOutlined',
            value: BorderRightOutlined,
          },
          {
            label: 'BorderTopOutlined',
            value: BorderTopOutlined,
          },
          {
            label: 'BorderVerticleOutlined',
            value: BorderVerticleOutlined,
          },
          {
            label: 'PicCenterOutlined',
            value: PicCenterOutlined,
          },
          {
            label: 'PicLeftOutlined',
            value: PicLeftOutlined,
          },
          {
            label: 'PicRightOutlined',
            value: PicRightOutlined,
          },
          {
            label: 'RadiusBottomleftOutlined',
            value: RadiusBottomleftOutlined,
          },
          {
            label: 'RadiusBottomrightOutlined',
            value: RadiusBottomrightOutlined,
          },
          {
            label: 'RadiusUpleftOutlined',
            value: RadiusUpleftOutlined,
          },
          {
            label: 'RadiusUprightOutlined',
            value: RadiusUprightOutlined,
          },
          {
            label: 'FullscreenOutlined',
            value: FullscreenOutlined,
          },
          {
            label: 'FullscreenExitOutlined',
            value: FullscreenExitOutlined,
          },
        ],
      },
      {
        label: '提示建议性图标',
        children: [
          {
            label: 'QuestionOutlined',
            value: QuestionOutlined,
          },
          {
            label: 'QuestionCircleOutlined',
            value: QuestionCircleOutlined,
          },
          {
            label: 'PlusOutlined',
            value: PlusOutlined,
          },
          {
            label: 'PlusCircleOutlined',
            value: PlusCircleOutlined,
          },
          {
            label: 'PauseOutlined',
            value: PauseOutlined,
          },
          {
            label: 'PauseCircleOutlined',
            value: PauseCircleOutlined,
          },
          {
            label: 'MinusOutlined',
            value: MinusOutlined,
          },
          {
            label: 'MinusCircleOutlined',
            value: MinusCircleOutlined,
          },
          {
            label: 'PlusSquareOutlined',
            value: PlusSquareOutlined,
          },
          {
            label: 'MinusSquareOutlined',
            value: MinusSquareOutlined,
          },
          {
            label: 'InfoOutlined',
            value: InfoOutlined,
          },
          {
            label: 'InfoCircleOutlined',
            value: InfoCircleOutlined,
          },
          {
            label: 'ExclamationOutlined',
            value: ExclamationOutlined,
          },
          {
            label: 'ExclamationCircleOutlined',
            value: ExclamationCircleOutlined,
          },
          {
            label: 'CloseCircleOutlined',
            value: CloseCircleOutlined,
          },
          {
            label: 'CloseOutlined',
            value: CloseOutlined,
          },
          {
            label: 'CloseSquareOutlined',
            value: CloseSquareOutlined,
          },
          {
            label: 'CheckOutlined',
            value: CheckOutlined,
          },
          {
            label: 'CheckCircleOutlined',
            value: CheckCircleOutlined,
          },
          {
            label: 'CheckSquareOutlined',
            value: CheckSquareOutlined,
          },
          {
            label: 'ClockCircleOutlined',
            value: ClockCircleOutlined,
          },
          {
            label: 'WarningOutlined',
            value: WarningOutlined,
          },
          {
            label: 'IssuesCloseOutlined',
            value: IssuesCloseOutlined,
          },
          {
            label: 'StopOutlined',
            value: StopOutlined,
          },
        ],
      },
      {
        label: '编辑类图标',
        children: [
          {
            label: 'EditOutlined',
            value: EditOutlined,
          },
          {
            label: 'FormOutlined',
            value: FormOutlined,
          },
          {
            label: 'CopyOutlined',
            value: CopyOutlined,
          },
          {
            label: 'ScissorOutlined',
            value: ScissorOutlined,
          },
          {
            label: 'DeleteOutlined',
            value: DeleteOutlined,
          },
          {
            label: 'SnippetsOutlined',
            value: SnippetsOutlined,
          },
          {
            label: 'DiffOutlined',
            value: DiffOutlined,
          },
          {
            label: 'HighlightOutlined',
            value: HighlightOutlined,
          },
          {
            label: 'AlignCenterOutlined',
            value: AlignCenterOutlined,
          },
          {
            label: 'AlignLeftOutlined',
            value: AlignLeftOutlined,
          },
          {
            label: 'AlignRightOutlined',
            value: AlignRightOutlined,
          },
          {
            label: 'BgColorsOutlined',
            value: BgColorsOutlined,
          },
          {
            label: 'BoldOutlined',
            value: BoldOutlined,
          },
          {
            label: 'ItalicOutlined',
            value: ItalicOutlined,
          },
          {
            label: 'UnderlineOutlined',
            value: UnderlineOutlined,
          },
          {
            label: 'StrikethroughOutlined',
            value: StrikethroughOutlined,
          },
          {
            label: 'RedoOutlined',
            value: RedoOutlined,
          },
          {
            label: 'UndoOutlined',
            value: UndoOutlined,
          },
          {
            label: 'ZoomInOutlined',
            value: ZoomInOutlined,
          },
          {
            label: 'ZoomOutOutlined',
            value: ZoomOutOutlined,
          },
          {
            label: 'FontColorsOutlined',
            value: FontColorsOutlined,
          },
          {
            label: 'FontSizeOutlined',
            value: FontSizeOutlined,
          },
          {
            label: 'LineHeightOutlined',
            value: LineHeightOutlined,
          },
          {
            label: 'DashOutlined',
            value: DashOutlined,
          },
          {
            label: 'SmallDashOutlined',
            value: SmallDashOutlined,
          },
          {
            label: 'SortAscendingOutlined',
            value: SortAscendingOutlined,
          },
          {
            label: 'SortDescendingOutlined',
            value: SortDescendingOutlined,
          },
          {
            label: 'DragOutlined',
            value: DragOutlined,
          },
          {
            label: 'OrderedListOutlined',
            value: OrderedListOutlined,
          },
          {
            label: 'UnorderedListOutlined',
            value: UnorderedListOutlined,
          },
          {
            label: 'RadiusSettingOutlined',
            value: RadiusSettingOutlined,
          },
          {
            label: 'ColumnWidthOutlined',
            value: ColumnWidthOutlined,
          },
          {
            label: 'ColumnHeightOutlined',
            value: ColumnHeightOutlined,
          },
        ],
      },
      {
        label: '数据类图标',
        children: [
          {
            label: 'AreaChartOutlined',
            value: AreaChartOutlined,
          },
          {
            label: 'PieChartFilled',
            value: PieChartFilled,
          },
          {
            label: 'BarChartOutlined',
            value: BarChartOutlined,
          },
          {
            label: 'DotChartOutlined',
            value: DotChartOutlined,
          },
          {
            label: 'LineChartOutlined',
            value: LineChartOutlined,
          },
          {
            label: 'RadarChartOutlined',
            value: RadarChartOutlined,
          },
          {
            label: 'HeartOutlined',
            value: HeartOutlined,
          },
          {
            label: 'FallOutlined',
            value: FallOutlined,
          },
          {
            label: 'RiseOutlined',
            value: RiseOutlined,
          },
          {
            label: 'StockOutlined',
            value: StockOutlined,
          },
          {
            label: 'BoxPlotOutlined',
            value: BoxPlotOutlined,
          },
          {
            label: 'FundOutlined',
            value: FundOutlined,
          },
          {
            label: 'SlidersOutlined',
            value: SlidersOutlined,
          },
        ],
      },
      {
        label: '网站通用图标',
        children: [
          {
            label: 'AccountBookOutlined',
            value: AccountBookOutlined,
          },
          {
            label: 'AimOutlined',
            value: AimOutlined,
          },
          {
            label: 'AlertOutlined',
            value: AlertOutlined,
          },
          {
            label: 'ApartmentOutlined',
            value: ApartmentOutlined,
          },
          {
            label: 'ApiOutlined',
            value: ApiOutlined,
          },
          {
            label: 'AppstoreOutlined',
            value: AppstoreOutlined,
          },
          {
            label: 'AppstoreAddOutlined',
            value: AppstoreAddOutlined,
          },
          {
            label: 'AudioOutlined',
            value: AudioOutlined,
          },
          {
            label: 'AudioMutedOutlined',
            value: AudioMutedOutlined,
          },
          {
            label: 'AuditOutlined',
            value: AuditOutlined,
          },
          {
            label: 'BankOutlined',
            value: BankOutlined,
          },
          {
            label: 'BarcodeOutlined',
            value: BarcodeOutlined,
          },
          {
            label: 'BarsOutlined',
            value: BarsOutlined,
          },
          {
            label: 'BellOutlined',
            value: BellOutlined,
          },
          {
            label: 'BlockOutlined',
            value: BlockOutlined,
          },
          {
            label: 'BookOutlined',
            value: BookOutlined,
          },
          {
            label: 'BorderOutlined',
            value: BorderOutlined,
          },
          {
            label: 'BorderlessTableOutlined',
            value: BorderlessTableOutlined,
          },
          {
            label: 'BranchesOutlined',
            value: BranchesOutlined,
          },
          {
            label: 'BugOutlined',
            value: BugOutlined,
          },
          {
            label: 'BuildOutlined',
            value: BuildOutlined,
          },
          {
            label: 'BulbOutlined',
            value: BulbOutlined,
          },
          {
            label: 'CalculatorOutlined',
            value: CalculatorOutlined,
          },
          {
            label: 'CalendarOutlined',
            value: CalendarOutlined,
          },
          {
            label: 'CameraOutlined',
            value: CameraOutlined,
          },
          {
            label: 'CarOutlined',
            value: CarOutlined,
          },
          {
            label: 'CarryOutFilled',
            value: CarryOutFilled,
          },
          {
            label: 'CiCircleOutlined',
            value: CiCircleOutlined,
          },
          {
            label: 'CiOutlined',
            value: CiOutlined,
          },
          {
            label: 'ClearOutlined',
            value: ClearOutlined,
          },
          {
            label: 'CloudOutlined',
            value: CloudOutlined,
          },
          {
            label: 'CloudDownloadOutlined',
            value: CloudDownloadOutlined,
          },
          {
            label: 'CloudServerOutlined',
            value: CloudServerOutlined,
          },
          {
            label: 'CloudSyncOutlined',
            value: CloudSyncOutlined,
          },
          {
            label: 'CloudUploadOutlined',
            value: CloudUploadOutlined,
          },
          {
            label: 'ClusterOutlined',
            value: ClusterOutlined,
          },
          {
            label: 'CodeOutlined',
            value: CodeOutlined,
          },
          {
            label: 'CoffeeOutlined',
            value: CoffeeOutlined,
          },
          {
            label: 'CommentOutlined',
            value: CommentOutlined,
          },
          {
            label: 'CompassOutlined',
            value: CompassOutlined,
          },
          {
            label: 'CompressOutlined',
            value: CompressOutlined,
          },
          {
            label: 'ConsoleSqlOutlined',
            value: ConsoleSqlOutlined,
          },
          {
            label: 'ContactsOutlined',
            value: ContactsOutlined,
          },
          {
            label: 'ContainerOutlined',
            value: ContainerOutlined,
          },
          {
            label: 'ControlOutlined',
            value: ControlOutlined,
          },
          {
            label: 'CopyrightCircleOutlined',
            value: CopyrightCircleOutlined,
          },
          {
            label: 'CopyrightOutlined',
            value: CopyrightOutlined,
          },
          {
            label: 'CreditCardOutlined',
            value: CreditCardOutlined,
          },
          {
            label: 'CrownOutlined',
            value: CrownOutlined,
          },
          {
            label: 'CustomerServiceOutlined',
            value: CustomerServiceOutlined,
          },
          {
            label: 'DashboardOutlined',
            value: DashboardOutlined,
          },
          {
            label: 'DatabaseOutlined',
            value: DatabaseOutlined,
          },
          {
            label: 'DeleteColumnOutlined',
            value: DeleteColumnOutlined,
          },
          {
            label: 'DeleteRowOutlined',
            value: DeleteRowOutlined,
          },
          {
            label: 'DeliveredProcedureOutlined',
            value: DeliveredProcedureOutlined,
          },
          {
            label: 'DeploymentUnitOutlined',
            value: DeploymentUnitOutlined,
          },
          {
            label: 'DesktopOutlined',
            value: DesktopOutlined,
          },
          {
            label: 'DingdingOutlined',
            value: DingdingOutlined,
          },
          {
            label: 'DisconnectOutlined',
            value: DisconnectOutlined,
          },
          {
            label: 'DislikeOutlined',
            value: DislikeOutlined,
          },
          {
            label: 'DollarCircleOutlined',
            value: DollarCircleOutlined,
          },
          {
            label: 'DollarOutlined',
            value: DollarOutlined,
          },
          {
            label: 'DownloadOutlined',
            value: DownloadOutlined,
          },
          {
            label: 'EllipsisOutlined',
            value: EllipsisOutlined,
          },
          {
            label: 'EnvironmentOutlined',
            value: EnvironmentOutlined,
          },
          {
            label: 'EuroCircleOutlined',
            value: EuroCircleOutlined,
          },
          {
            label: 'EuroOutlined',
            value: EuroOutlined,
          },
          {
            label: 'ExceptionOutlined',
            value: ExceptionOutlined,
          },
          {
            label: 'ExpandAltOutlined',
            value: ExpandAltOutlined,
          },
          {
            label: 'ExpandOutlined',
            value: ExpandOutlined,
          },
          {
            label: 'ExperimentOutlined',
            value: ExperimentOutlined,
          },
          {
            label: 'ExportOutlined',
            value: ExportOutlined,
          },
          {
            label: 'EyeOutlined',
            value: EyeOutlined,
          },
          {
            label: 'EyeInvisibleOutlined',
            value: EyeInvisibleOutlined,
          },
          {
            label: 'FieldBinaryOutlined',
            value: FieldBinaryOutlined,
          },
          {
            label: 'FieldNumberOutlined',
            value: FieldNumberOutlined,
          },
          {
            label: 'FieldStringOutlined',
            value: FieldStringOutlined,
          },
          {
            label: 'FieldTimeOutlined',
            value: FieldTimeOutlined,
          },
          {
            label: 'FileAddFilled',
            value: FileAddFilled,
          },
          {
            label: 'FileDoneOutlined',
            value: FileDoneOutlined,
          },
          {
            label: 'FileExcelOutlined',
            value: FileExcelOutlined,
          },
          {
            label: 'FileExclamationOutlined',
            value: FileExclamationOutlined,
          },
          {
            label: 'FileOutlined',
            value: FileOutlined,
          },
          {
            label: 'FileGifOutlined',
            value: FileGifOutlined,
          },
          {
            label: 'FileImageOutlined',
            value: FileImageOutlined,
          },
          {
            label: 'FileJpgOutlined',
            value: FileJpgOutlined,
          },
          {
            label: 'FileMarkdownOutlined',
            value: FileMarkdownOutlined,
          },
          {
            label: 'FilePdfOutlined',
            value: FilePdfOutlined,
          },
          {
            label: 'FilePptOutlined',
            value: FilePptOutlined,
          },
          {
            label: 'FileProtectOutlined',
            value: FileProtectOutlined,
          },
          {
            label: 'FileSearchOutlined',
            value: FileSearchOutlined,
          },
          {
            label: 'FileSyncOutlined',
            value: FileSyncOutlined,
          },
          {
            label: 'FileTextOutlined',
            value: FileTextOutlined,
          },
          {
            label: 'FileUnknownOutlined',
            value: FileUnknownOutlined,
          },
          {
            label: 'FileWordOutlined',
            value: FileWordOutlined,
          },
          {
            label: 'FileZipOutlined',
            value: FileZipOutlined,
          },
          {
            label: 'FilterOutlined',
            value: FilterOutlined,
          },
          {
            label: 'FireOutlined',
            value: FireOutlined,
          },
          {
            label: 'FlagOutlined',
            value: FlagOutlined,
          },
          {
            label: 'FolderOutlined',
            value: FolderOutlined,
          },
          {
            label: 'FolderAddOutlined',
            value: FolderAddOutlined,
          },
          {
            label: 'FolderOpenOutlined',
            value: FolderOpenOutlined,
          },
          {
            label: 'FolderViewOutlined',
            value: FolderViewOutlined,
          },
          {
            label: 'ForkOutlined',
            value: ForkOutlined,
          },
          {
            label: 'FormatPainterOutlined',
            value: FormatPainterOutlined,
          },
          {
            label: 'FrownOutlined',
            value: FrownOutlined,
          },
          {
            label: 'FunctionOutlined',
            value: FunctionOutlined,
          },
          {
            label: 'FundProjectionScreenOutlined',
            value: FundProjectionScreenOutlined,
          },
          {
            label: 'FundViewOutlined',
            value: FundViewOutlined,
          },
          {
            label: 'FunnelPlotOutlined',
            value: FunnelPlotOutlined,
          },
          {
            label: 'GatewayOutlined',
            value: GatewayOutlined,
          },
          {
            label: 'GifOutlined',
            value: GifOutlined,
          },
          {
            label: 'GiftOutlined',
            value: GiftOutlined,
          },
          {
            label: 'GlobalOutlined',
            value: GlobalOutlined,
          },
          {
            label: 'GoldOutlined',
            value: GoldOutlined,
          },
          {
            label: 'GroupOutlined',
            value: GroupOutlined,
          },
          {
            label: 'HddOutlined',
            value: HddOutlined,
          },
          {
            label: 'HistoryOutlined',
            value: HistoryOutlined,
          },
          {
            label: 'HolderOutlined',
            value: HolderOutlined,
          },
          {
            label: 'HomeOutlined',
            value: HomeOutlined,
          },
          {
            label: 'HourglassOutlined',
            value: HourglassOutlined,
          },
          {
            label: 'IdcardOutlined',
            value: IdcardOutlined,
          },
          {
            label: 'ImportOutlined',
            value: ImportOutlined,
          },
          {
            label: 'InboxOutlined',
            value: InboxOutlined,
          },
          {
            label: 'InsertRowAboveOutlined',
            value: InsertRowAboveOutlined,
          },
          {
            label: 'InsertRowBelowOutlined',
            value: InsertRowBelowOutlined,
          },
          {
            label: 'InsertRowLeftOutlined',
            value: InsertRowLeftOutlined,
          },
          {
            label: 'InsertRowRightOutlined',
            value: InsertRowRightOutlined,
          },
          {
            label: 'InsuranceOutlined',
            value: InsuranceOutlined,
          },
          {
            label: 'InteractionOutlined',
            value: InteractionOutlined,
          },
          {
            label: 'KeyOutlined',
            value: KeyOutlined,
          },
          {
            label: 'LaptopOutlined',
            value: LaptopOutlined,
          },
          {
            label: 'LaptopOutlined',
            value: LaptopOutlined,
          },
          { label: 'LayoutOutlined', value: LayoutOutlined },
          { label: 'LikeOutlined', value: LikeOutlined },
          { label: 'LineOutlined', value: LineOutlined },
          { label: 'LinkOutlined', value: LinkOutlined },
          { label: 'Loading3QuartersOutlined', value: Loading3QuartersOutlined },
          { label: 'LoadingOutlined', value: LoadingOutlined },
          { label: 'LockOutlined', value: LockOutlined },
          { label: 'MacCommandOutlined', value: MacCommandOutlined },
          { label: 'MailOutlined', value: MailOutlined },
          { label: 'ManOutlined', value: ManOutlined },
          { label: 'MedicineBoxOutlined', value: MedicineBoxOutlined },
          { label: 'MehOutlined', value: MehOutlined },
          { label: 'MenuOutlined', value: MenuOutlined },
          { label: 'MergeCellsOutlined', value: MergeCellsOutlined },
          { label: 'MessageOutlined', value: MessageOutlined },
          { label: 'MobileOutlined', value: MobileOutlined },
          { label: 'MoneyCollectOutlined', value: MoneyCollectOutlined },
          { label: 'MonitorOutlined', value: MonitorOutlined },
          { label: 'MoreOutlined', value: MoreOutlined },
          { label: 'NodeCollapseOutlined', value: NodeCollapseOutlined },
          { label: 'NodeExpandOutlined', value: NodeExpandOutlined },
          { label: 'NodeIndexOutlined', value: NodeIndexOutlined },
          { label: 'NotificationOutlined', value: NotificationOutlined },
          { label: 'NumberOutlined', value: NumberOutlined },
          { label: 'OneToOneOutlined', value: OneToOneOutlined },
          { label: 'PaperClipOutlined', value: PaperClipOutlined },
          { label: 'PartitionOutlined', value: PartitionOutlined },
          { label: 'PayCircleOutlined', value: PayCircleOutlined },
          { label: 'PercentageOutlined', value: PercentageOutlined },
          { label: 'PhoneOutlined', value: PhoneOutlined },
          { label: 'PictureOutlined', value: PictureOutlined },
          { label: 'PlaySquareOutlined', value: PlaySquareOutlined },
          { label: 'PoundCircleOutlined', value: PoundCircleOutlined },
          { label: 'PoundOutlined', value: PoundOutlined },
          { label: 'PoweroffOutlined', value: PoweroffOutlined },
          { label: 'PrinterOutlined', value: PrinterOutlined },
          { label: 'ProfileOutlined', value: ProfileOutlined },
          { label: 'ProjectOutlined', value: ProjectOutlined },
          { label: 'PropertySafetyOutlined', value: PropertySafetyOutlined },
          { label: 'PullRequestOutlined', value: PullRequestOutlined },
          { label: 'PushpinOutlined', value: PushpinOutlined },
          { label: 'QrcodeOutlined', value: QrcodeOutlined },
          { label: 'ReadOutlined', value: ReadOutlined },
          { label: 'ReconciliationOutlined', value: ReconciliationOutlined },
          { label: 'RedEnvelopeOutlined', value: RedEnvelopeOutlined },
          { label: 'ReloadOutlined', value: ReloadOutlined },
          { label: 'RestOutlined', value: RestOutlined },
          { label: 'RobotOutlined', value: RobotOutlined },
          { label: 'RocketOutlined', value: RocketOutlined },
          { label: 'RotateLeftOutlined', value: RotateLeftOutlined },
          { label: 'RotateRightOutlined', value: RotateRightOutlined },
          { label: 'SafetyCertificateOutlined', value: SafetyCertificateOutlined },
          { label: 'SafetyOutlined', value: SafetyOutlined },
          { label: 'SaveOutlined', value: SaveOutlined },
          { label: 'ScanOutlined', value: ScanOutlined },
          { label: 'ScheduleOutlined', value: ScheduleOutlined },
          { label: 'SearchOutlined', value: SearchOutlined },
          { label: 'SecurityScanOutlined', value: SecurityScanOutlined },
          { label: 'SelectOutlined', value: SelectOutlined },
          { label: 'SendOutlined', value: SendOutlined },
          { label: 'SettingOutlined', value: SettingOutlined },
          { label: 'ShakeOutlined', value: ShakeOutlined },
          { label: 'ShareAltOutlined', value: ShareAltOutlined },
          { label: 'ShopOutlined', value: ShopOutlined },
          { label: 'ShoppingCartOutlined', value: ShoppingCartOutlined },
          { label: 'ShoppingOutlined', value: ShoppingOutlined },
          { label: 'SisternodeOutlined', value: SisternodeOutlined },
          { label: 'SkinOutlined', value: SkinOutlined },
          { label: 'SmileOutlined', value: SmileOutlined },
          { label: 'SolutionOutlined', value: SolutionOutlined },
          { label: 'SoundOutlined', value: SoundOutlined },
          { label: 'SplitCellsOutlined', value: SplitCellsOutlined },
          { label: 'StarOutlined', value: StarOutlined },
          { label: 'SubnodeOutlined', value: SubnodeOutlined },
          { label: 'SwitcherOutlined', value: SwitcherOutlined },
          { label: 'SyncOutlined', value: SyncOutlined },
          { label: 'TableOutlined', value: TableOutlined },
          { label: 'TabletOutlined', value: TabletOutlined },
          { label: 'TagOutlined', value: TagOutlined },
          { label: 'TagsOutlined', value: TagsOutlined },
          { label: 'TeamOutlined', value: TeamOutlined },
          { label: 'ThunderboltOutlined', value: ThunderboltOutlined },
          { label: 'ToTopOutlined', value: ToTopOutlined },
          { label: 'ToolOutlined', value: ToolOutlined },
          { label: 'TrademarkCircleOutlined', value: TrademarkCircleOutlined },
          { label: 'TrademarkOutlined', value: TrademarkOutlined },
          { label: 'TransactionOutlined', value: TransactionOutlined },
          { label: 'TranslationOutlined', value: TranslationOutlined },
          { label: 'TrophyOutlined', value: TrophyOutlined },
          { label: 'UngroupOutlined', value: UngroupOutlined },
          { label: 'UnlockFilled', value: UnlockFilled },
          { label: 'UploadOutlined', value: UploadOutlined },
          { label: 'UserOutlined', value: UserOutlined },
          { label: 'UserAddOutlined', value: UserAddOutlined },
          { label: 'UserDeleteOutlined', value: UserDeleteOutlined },
          { label: 'UserSwitchOutlined', value: UserSwitchOutlined },
          { label: 'UsergroupAddOutlined', value: UsergroupAddOutlined },
          { label: 'UsergroupDeleteOutlined', value: UsergroupDeleteOutlined },
          { label: 'VerifiedOutlined', value: VerifiedOutlined },
          { label: 'VideoCameraAddOutlined', value: VideoCameraAddOutlined },
          { label: 'VideoCameraOutlined', value: VideoCameraOutlined },
          { label: 'WalletOutlined', value: WalletOutlined },
          { label: 'WhatsAppOutlined', value: WhatsAppOutlined },
          { label: 'WifiOutlined', value: WifiOutlined },
          { label: 'WomanOutlined', value: WomanOutlined },
          { label: 'UsbOutlined', value: UsbOutlined },
        ],
      },
    ],
  },
  {
    label: '实底风格',
    value: [
      {
        label: '编辑类图标',
        children: [
          { label: 'EditFilled', value: EditFilled },
          { label: 'CopyFilled', value: CopyFilled },
          { label: 'DeleteFilled', value: DeleteFilled },
          { label: 'SnippetsFilled', value: SnippetsFilled },
          { label: 'DiffFilled', value: DiffFilled },
          { label: 'HighlightFilled', value: HighlightFilled },
        ],
      },
    ],
  },
  {
    label: '双色风格',
    value: [
      {
        label: '编辑类图标',
        children: [
          { label: 'EditTwoTone', value: EditTwoTone },
          { label: 'CopyTwoTone', value: CopyTwoTone },
          { label: 'DeleteTwoTone', value: DeleteTwoTone },
          { label: 'SnippetsTwoTone', value: SnippetsTwoTone },
          { label: 'DiffTwoTone', value: DiffTwoTone },
          { label: 'HighlightTwoTone', value: HighlightTwoTone },
        ],
      },
    ],
  },
];
